apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-form #ชื่อของ angular app
spec:
  selector:
    matchLabels:
      app: simple-form #ชื่อของ angular app
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-form #ชื่อของ angular app
    spec:
      containers:
        - name: simple-form-app #ชื่อของ docker ที่สร้างขึ้นจาก Dockerfile
          image: angular/simple-form:v1 #ชื่อของ docker images ที่สร้างขึ้นจาก Dockerfile
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Never
          ports:
            - containerPort:  80