apiVersion: v1
kind: Service
metadata:
  name: simple-form-service #ชื่อของ angular app service
  namespace: default
spec:
  selector:
    app: simple-form #ชื่อของ angular app deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 90
      targetPort: 80