---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-form-jenkins #ชื่อของ angular app
spec:
  selector:
    matchLabels:
      app: simple-form-jenkins #ชื่อของ angular app
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-form-jenkins #ชื่อของ angular app
    spec:
      containers:
        - name: simple-form-jenkins-app #ชื่อของ docker ที่สร้างขึ้นจาก Dockerfile
          image: angular/simple-form-jenkins:v1 #ชื่อของ docker images ที่สร้างขึ้นจาก Dockerfile
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Never
          ports:
            - containerPort:  80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: simple-form-jenkins-svc
  name: simple-form-jenkins-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30200 # กำหนดหมายเลข NodePort (30000-32767)
  selector:
    run: simple-form-jenkins
  type: NodePort # เพิ่มเติมในส่วนของประเภทให้เป็น NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-form-ingress
  namespace: default
spec:
  rules:
  - host: angular13-simple-form.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-form-jenkins-svc
            port:
              number: 80