---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-form-jenkins #ชื่อของ angular app
spec:
  selector:
    matchLabels:
      app: simple-form-jenkins #ชื่อของ angular app
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-form-jenkins #ชื่อของ angular app
    spec:
      containers:
        - name: simple-form-jenkins-app #ชื่อของ docker ที่สร้างขึ้นจาก Dockerfile
          image: angular/simple-form-jenkins:v1 #ชื่อของ docker images ที่สร้างขึ้นจาก Dockerfile
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Never
          ports:
            - containerPort:  80
---
apiVersion: v1
kind: Service # ประเภทของ Resource
metadata:
  name: simple-form-jenkins-service # ชื่อของ Service
spec:
  selector:
    app: simple-form-jenkins
  type: NodePort
  ports:
  - name: simple-form-jenkins
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress # ประเภทของ Resource
metadata:
  name: simple-form-ingress # ชื่อของ Ingress
  namespace: default
spec:
  rules: # ส่วนของการกำหนด Rule ให้กับ Ingress
    - host: "angular13-simple-form.com" # Hostname ที่จะให้ User เข้าใช้งาน
      http:
        paths:
        - path: / # Path ที่จะให้เข้ามาใช้งาน Pod
          pathType: Prefix # ประเภทของการ Match Path
          backend: # ส่วนของการระบุ Service ที่จะให้นำทางไปยัง Pod
            service:
              name: simple-form-jenkins-service # ชื่อของ Service
              port:
                number: 80 #  Port ของ Service