---
apiVersion: v1
kind: Service
metadata:
  name: simple-form-jenkins-service #ชื่อของ angular app service
  namespace: default
spec:
  selector:
    app: simple-form-jenkins #ชื่อของ angular app deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-form-ingress
  namespace: default
spec:
  rules:
  - host: angular13-simple-form.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-form-jenkins-service
            port:
              number: 80