# (Without Jenkins) -------------------------------------------------------------
FROM nginx:alpine 
# COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
COPY ./dist/simple-form ./usr/share/nginx/html
# (Without Jenkins) -------------------------------------------------------------