pipeline {
    agent any

    stages {
        stage('Node Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('Angular Build') {
            steps {
                sh 'ng build --prod'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t angular/simple-form-jenkins:v1 -f docker/Dockerfile .'
            }
        }
        stage('Deploy K8S YAML') {
            steps {
                // sh 'kubectl create -f k8s/deploy-service.yaml'
                // sh 'kubectl create -f k8s/ingress.yaml'
                sh 'kubectl replace -f k8s/ingress.yaml'
            }
        }
    }
}