pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t angular/simple-form-jenkins:v1 -f docker/Dockerfile .'
            }
        }
        stage('Deploy K8S YAML') {
            steps {
                sh 'kubectl create -f k8s/deploy-service.yaml'
            }
        }
    }
}